import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Baby-Wash",
    price: 500,
    categoryName: "babycare",
    rating:4,
    isLatest:false,
    img:"assets/Products/baby1.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Lip-Balm",
    price: 100,
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin7.jpg",
    inStock:false,
  },
  {
    _id: uuid(),
    title: "Sandal-Perfume",
    price: 700,
    categoryName: "perfumes",
    rating:4,
    isLatest:true,
    img:"assets/Products/newper2.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Baby-Conditioner",
    price: 400,
    categoryName: "babycare",
    rating:5,
    isLatest:true,
    img:"assets/Products/baby2.webp",
    inStock:true,
  },
 

  {
    _id: uuid(),
    title: "Lip-Oil",
    price: 400,
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin6.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Nude-Lipstick",
    price: 800,
    categoryName: "cosmetics",
    rating:3,
    isLatest:false,
    img:"assets/Products/cos1.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Eye-Linear",
    price: 400,
    categoryName: "cosmetics",
    rating:5,
    isLatest:false,
    img:"assets/Products/cos2.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Lip-Serum",
    price: 200,
    categoryName: "cosmetics",
    rating:5,
    isLatest:false,
    img:"assets/Products/cos3.webp",
    inStock:true,
  },
  
  {
    _id: uuid(),
    title: "Eye-Mascara",
    price: 700,
    categoryName: "cosmetics",
    rating:5,
    isLatest:false,
    img:"assets/Products/cos5.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Light-Perfume",
    price: 700,
    categoryName: "perfumes",
    rating:3,
    isLatest:false,
    img:"assets/Products/per3.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Face-Higlighter",
    price: 1000,
    categoryName: "cosmetics",
    rating:4,
    isLatest:true,
    img:"assets/Products/cos6.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "EyeShadow-Palette",
    price: 800,
    categoryName: "cosmetics",
    rating:2,
    isLatest:false,
    img:"assets/Products/cos7.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Face-Oil",
    price: 400,
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin5.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Lipstick",
    price: 400,
    categoryName: "cosmetics",
    rating:5,
    isLatest:false,
    img:"assets/Products/cos8.webp",
    inStock:true,
  },
  
 
  {
    _id: uuid(),
    title: "Nude-Lipstick",
    price: 500,
    categoryName: "cosmetics",
    rating:4,
    isLatest:false,
    img:"assets/Products/cos11.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Lipstick",
    price: 600,
    categoryName: "cosmetics",
    rating:4,
    isLatest:false,
    img:"assets/Products/cos9.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Pink-Lipstick",
    price:800,
    categoryName: "cosmetics",
    rating:4,
    isLatest:true,
    img:"assets/Products/newcos1.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Face-Mask",
    price: 800,
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin4.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Eye-linear",
    price: 400,
    categoryName: "cosmetics",
    rating:4,
    isLatest:true,
    img:"assets/Products/newcos2.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Rossy-Perfume",
    price: 900,
    categoryName: "perfumes",
    rating:4,
    isLatest:true,
    img:"assets/Products/newper1.jpg",
    inStock:true,
  },

 
  {
    _id: uuid(),
    title: "Nude-Highlighter",
    price: 800,
    categoryName: "cosmetics",
    rating:4,
    isLatest:false,
    img:"assets/Products/cos10.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "EyeShadow-Palette",
    price: 1000,
    categoryName: "cosmetics",
    rating:2,
    isLatest:false,
    img:"assets/Products/cos4.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Face-Wash",
    price: "400",
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin3.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Night-Cream",
    price: 900,
    categoryName: "skincare",
    rating:4,
    isLatest:true,
    img:"assets/Products/newskin1.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Night-Perfume",
    price: 1000,
    categoryName: "perfumes",
    rating:4,
    isLatest:false,
    img:"assets/Products/per1.jpg",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "BlueLights-Perfume",
    price:500,
    categoryName: "perfumes",
    rating:5,
    isLatest:false,
    img:"assets/Products/per2.webp",
    inStock:true,
  },
  
  {
    _id: uuid(),
    title: "Tree-Oil",
    price: 400,
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin8.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Baby-Sampoo",
    price: "700",
    categoryName: "babycare",
    rating:5,
    isLatest:true,
    img:"assets/Products/baby4.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Party-Perfume",
    price: 600,
    categoryName: "perfumes",
    rating:4,
    isLatest:false,
    img:"assets/Products/per4.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Baby-Cream",
    price: 300,
    categoryName: "babycare",
    rating:5,
    isLatest:false,
    img:"assets/Products/baby3.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Glam-Perfume",
    price:1000,
    categoryName: "perfumes",
    rating:4,
    isLatest:false,
    img:"assets/Products/per5.jpg",
    inStock:false,
  },
  {
    _id: uuid(),
    title: "Milk-Toner",
    price: 800,
    categoryName: "skincare",
    rating:1,
    isLatest:false,
    img:"assets/Products/skin1.webp",
    inStock:true,
  },
  {
    _id: uuid(),
    title: "Eye-Cream",
    price:900,
    categoryName: "skincare",
    rating:4,
    isLatest:false,
    img:"assets/Products/skin2.webp",
    inStock:true,
  },
];
