export {getSortedProducts} from "./SortProducts"
export {getRatedProducts} from "./FilterbyRatings"
export {getPricedProducts} from "./FilterbyPrice"
export {getLatestProducts } from "./FilterbyLatest"
export {getFilteredCatProducts} from "./FilterbyCategory"
export {getOutofStocksProducts} from "./FilterbyStocks"
